name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    name: 'Check Formatting'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check Formatting
        run: cargo fmt --check
    continue-on-error: true
  lint:
    name: 'Lint Checks'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libclipper2 libassimp-dev libtbb-dev
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Lint Checks
        run: cargo clippy --all --all-targets --all-features -- -D warnings
    continue-on-error: true